name: Deploy SmartDuka to Firebase Hosting

on:
  push:
    branches:
      - main  # Mfumo utarusha kodi kila ukituma kwenye branch ya main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Kuvuta kodi zako kutoka GitHub
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Kuweka na kuandaa Node.js kwenye seva ya GitHub
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Kuweka Firebase Tools kwenye seva ya GitHub
      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      # 4. Kurusha kodi zako kwenda Firebase live kwa kutumia ile Token yetu ya siri
      - name: Deploy to Firebase Hosting
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
